name: value_retriever
description: A package that creates a value controller that allows a value to be retrieved
version: 0.0.1
repository: https://github.com/erickzanardo/value_retriever

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
